name: Deploy Vite React App to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Move main index file to docs
        run: |
          if([ -f "index.html" ] && [! -f "docs/index.html"]); then
            echo "moving main index file"
            mv index.html docs/
          else
            echo "index file already existing in docs/"
          fi
      - name: Move normal JS projects to docs
        run: |
          for dir in */ ; do
            if [ -f "$dir/index.html" ] && [ ! -f "$dir/package.json" ]; then
              echo "Copying $dir to docs/"
              cp -r "$dir" "docs/"
            fi
          done
      - name: Install dependencies and build
        run: |
          for dir in */ ; do
            if [ -f "$dir/package.json" ]; then
              cd  "$dir"
              echo "Installing dependencies for $dir"
              npm install
              npm run build
              mv dist "../docs/$dir"
              cd ..
            fi
          done
          touch docs/.nojekyll
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs
          git commit -m "Deploy updates"
          git push
